In [1]:
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(x_train.shape)

(60000, 28, 28)


In [4]:
# reshape from 28,28 to one 784 dimension
x_train_flat = np.reshape(x_train, (60000, 784), copy=True)
x_test_flat = np.reshape(x_test, (10000, 784), copy=True)

print(x_train_flat.shape)

(60000, 784)


In [5]:
# normalise to values between 0-1 instead of 0-255
x_train_flat = x_train_flat / 255
x_test_flat = x_test_flat / 255

In [6]:
# recategorise values to numerical values 0-9
print(y_train[0:3])
print(np.unique(y_train))

y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

print(y_train[0:3])
print(np.unique(y_train))


[5 0 4]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
[0. 1.]


In [7]:
# Reshape the training and test data to right shapes and normalise
x_train_conv = np.reshape(x_train, (60000, 28, 28, 1), copy=True)
x_test_conv = np.reshape(x_test, (10000, 28, 28, 1), copy=True)

x_train_conv = x_train_conv / 255
x_test_conv = x_test_conv / 255

Write a simple function that achieves the convolution operation efficiently for two-
dimensional and three-dimensional inputs. This should allow you to input a set of
convolutional filters (‘kernels’ in Keras’s terminology) and an input layer (or image)
as inputs. The input layer should have a third dimension, representing a stack of
feature maps, and each filter should have a third dimension of corresponding size.
The function should output a number of two-dimensional feature maps
corresponding to the number of input filters, though these can be stacked into a
third dimensional like the input layer.


In [ ]:
def conv_operation(filter, input_layer):
    """
    Only handle cases where the input layer contains 1 or multiple stacked 2D images.
    The filter is always the same 2d filter applied to all images in the input layer.
    """
    

# ReLu

In [ ]:
def relu(feature_map):
    return np.maximum(feature_map, 0)

# Apply ReLU to the horizontal edge map
relu_horizontal = relu(result[0])

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
axes[0].imshow(result[0], cmap='gray')
axes[0].set_title('Before ReLU')
axes[1].imshow(relu_horizontal, cmap='gray')
axes[1].set_title('After ReLU (horizontal edges)')

for ax in axes:
    ax.axis('off')

plt.tight_layout()
plt.show()


# Apply ReLU to the vertical edge map
relu_vertical = relu(result[1])

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
axes[0].imshow(result[0], cmap='gray')
axes[0].set_title('Before ReLU')
axes[1].imshow(relu_vertical, cmap='gray')
axes[1].set_title('After ReLU (vertical edges)')

for ax in axes:
    ax.axis('off')

plt.tight_layout()
plt.show()


---

# maxPooling

In [ ]:
def maxpooling(feature_map, pool_size=2, stride=2):
    """
    params:
    - feature_map: 2D array representing the feature map to be pooled.
    - pool_size: size of the pooling window (default is 2).
    - stride: step size for moving the pooling window (default is 2).

    output:
    - pooled_feature_map: 2D array after applying max pooling.
    """
    in_h, in_w = feature_map.shape
    out_h = (in_h - pool_size) // stride + 1
    out_w = (in_w - pool_size) // stride + 1

    pooled_feature_map = np.zeros((out_h, out_w))

    for i in range(out_h):
        for j in range(out_w):
            h_start = i * stride
            h_end = h_start + pool_size
            w_start = j * stride
            w_end = w_start + pool_size

            pooled_feature_map[i, j] = np.max(feature_map[h_start:h_end, w_start:w_end])

    return pooled_feature_map